version: '3.8'

services:
  backend:
    build: .
    image: motbi_custom:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=motbiuser
      - DB_PASSWORD=motbipassword
      - DB_NAME=motbi

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: motbi
      MYSQL_USER: motbiuser
      MYSQL_PASSWORD: motbipassword
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
